name: Windows MSWin Build Tools

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  mswin:
    name: >-
      mswin vcpkg tools
    runs-on: windows-2022
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mswin
        timeout-minutes: 5

      - name: update vcpkg installation
        run:  |
          $env:VCPKG_ROOT = $env:VCPKG_INSTALLATION_ROOT
          cd $env:VCPKG_INSTALLATION_ROOT
          git pull -q
          ./bootstrap-vcpkg.bat
          echo "`n———————————— ./vcpkg list ————————————"
          ./vcpkg list
        timeout-minutes: 15

      - name: Update mswin tools 7z and Upload
        run:  ruby create_mswin_pkg.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 30
