name: MSYS2 GCC Package

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  msys2:
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy msys2 files to temp dir
        timeout-minutes: 10
        run: |
          $temp = $env:RUNNER_TEMP
          md $temp\msys64
          # copy current msys2 to temp folder, needed to determine what files to include
          # in zip file (only newer files)
          xcopy C:\msys64 $temp\msys64 /s /q

      - name: Set up Ruby
        timeout-minutes: 5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mingw

      - name: Update msys2
        timeout-minutes: 15
        run: ./update_msys2.ps1

      - name: Create MSYS2 tools 7z
        timeout-minutes: 10
        if: env.Create7z == 'yes'
        run: ruby create_msys2_pkg.rb

      - name: upload asset
        timeout-minutes: 5
        if: env.Create7z == 'yes'
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_tag: 'msys2-gcc-pkgs'
          release_name: msys2

  main:
    runs-on: windows-2022
    needs: msys2
    strategy:
      fail-fast: false
      matrix:
        include:
          - { gcc: mingw64, ruby: mingw }
          - { gcc: ucrt64 , ruby: ucrt  }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        timeout-minutes: 5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Update gcc
        timeout-minutes: 10
        run:  ruby create_gcc_pkg.rb ${{ matrix.gcc }}

      - name: upload asset
        if: env.Create7z == 'yes'
        timeout-minutes: 5
        uses: ./.github/actions/upload-binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_tag: 'msys2-gcc-pkgs'
          release_name: ${{ matrix.gcc }}
